### ISSUE TITLE
using it with angular 2

### ISSUE THREAD

**Issue by hem19** [phosphorjs/phosphor-dockpanel#17]
It's written in typescript which is a big bonus for me. I want to use it with angular 2 but not able to find any documentation on the same. Can you provide some documentation about using it with angular 2.

**Comment by sccolbert** [comment]
This repo is old. We've moved all development to a single repo:
https://github.com/phosphorjs/phosphor

Phosphor can be used with just about any other JS lib. Just use `Widget.attach` to attach a Phosphor widget to an existing DOM node.
