### ISSUE TITLE
Can you dock non tabbed panels with this library?

### ISSUE THREAD

**Issue by patrickliechty** [phosphorjs/phosphor-dockpanel#19]
Instead of tabbed panels, how would I just use a regular panel or container?  I would think the panel would have a title bar that you can use to move the panel.  Is that possible using Phosphor?

It appears that tabbed panels are the only ones that can be moved.  Is that true?

**Comment by patrickliechty** [comment]
It would be nice to drag a window using a thumb.  I would rather not have a title bar on the window.  Is that possible?

**Comment by sccolbert** [comment]
This is a good idea, and would make `DockPanel` really nice for creating dashboard type apps.

Currently, only tab panels are supported. We could potentially make them *look* like single panels with some clever CSS to stretch a single tab across the entire tab bar, but it wouldn't prevent you from adding other tabs to that area.

I'm open to ideas here for making this more flexible. It will take some work on `DockPanel`, but it shouldn't be too difficult.

**Comment by sccolbert** [comment]
@blink1073 @afshin @ellisonbg @jasongrout

**Comment by sccolbert** [comment]
moved issue to correct repo
